development:
  adapter: mysql2
  encoding: utf8
  reconnect: false  
  database: phv_development
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: phv_test
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000

production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: phv_production
    username: root
    password:
    socket: /var/run/mysqld/mysqld.sock
    pool: 5
    timeout: 5000
